### PR TITLE
Idiomatic 3

### PR DESCRIPTION
**Pull request by chris-ha458**
Of these commits 3d4d4c0 is the most interesting.

As is, only the bare minimum necessary to change `for` into `iter` was done.
It isnt faster as is, but the following could be done to optimize :  
1. since there are no outside side effects or dependency between elements (i think) rayon could be used.
2. filter_map is used in the bare minimum way. this could be combined with filter_maps to replace unwraps() or replace `if else`.  
3. General optimization of code could be done with regard to the current `map()`. for instance, I wonder if `encoding[encoding.len() - 2]` or  `if encoding.len() == 1 && encoding.first().unwrap() == "largesets"` couldn't be changed? I think a closer look is necessary, and I didn't want to change something without knowing and break it.

### CODE REVIEW

**Comment by chris-ha458** [comment]
8f6b960
is another complicated commit.
I did my best to document what the previous and new code does and how, but if there is any confusion, it might be a good idea to build some test cases to validate behavior.
In fact, I think I will break that down into multiple inlined `fn` so that we can more easily test the individual ranges.

**Comment by nickspring** [comment]
There are a lot of tests, however, they were disabled by mistake. Please take e a look or rebase on my PR. Actually, for each function, I have a small unit test.

**Comment by nickspring** [comment]
1. Rayon is good idea, but this code should be enabled optionally via feature (so final user can switch the mode).
3. Both these lines are from function-helper for perfomance test datasets loading. I would prefer to do not change it for consistence in our tests.

**Comment by chris-ha458** [comment]
I have merged from your PR.
>Both these lines are from function-helper for perfomance test datasets loading. I would prefer to do not change it for consistence in our tests.

Which lines are you talking about?

**Comment by nickspring** [comment]
PS. Also, in PR#9, I have removed round_float.

**Comment by chris-ha458** [comment]
> Rayon is good idea, but this code should be enabled optionally via feature (so final user can switch the mode).
I will keep that in mind. Unless you initiate the change I think implementing Rayon would be a very low priority for me.
Not because it won't be useful but it would require some discussion and choices. Also it can be a "cheat button" that hides many other potential opportunities for correct and clear code.

**Comment by nickspring** [comment]
> I have merged from your PR.
> 
> > Both these lines are from function-helper for perfomance test datasets loading. I would prefer to do not change it for consistence in our tests.
> 
> Which lines are you talking about?

 I wonder if encoding[encoding.len() - 2] or  if encoding.len() == 1 && encoding.first().unwrap() == "largesets" couldn't be changed? I think a closer look is necessary, and I didn't want to change something without knowing and break it.

**Comment by chris-ha458** [comment]
If semantic parity with other parts of the code or test is what you are looking for, would you be okay with it if we changed both parts of the code so they are implemented the same (either in code or semantically).

Unless of course there is a reason to want this specific version of implementation.

**Comment by nickspring** [comment]
> > Rayon is good idea, but this code should be enabled optionally via feature (so final user can switch the mode).
> 
> I will keep that in mind. Unless you initiate the change I think implementing Rayon would be a very low priority for me. Not because it won't be useful but it would require some discussion and choices. Also it can be a "cheat button" that hides many other potential opportunities for correct and clear code.

Yes, I understand. I plan to work on hash function replacement at this time. Rayon will be implemented later, not a goal right now.

**Comment by nickspring** [comment]
> If semantic parity with other parts of the code or test is what you are looking for, would you be okay with it if we changed both parts of the code so they are implemented the same (either in code or semantically).
> 
> Unless of course there is a reason to want this specific version of implementation.

If you're talking about `get_large_test_datasets`, it's just tests loader (helper). It can be changed, if results will be the same.

**Pull request merged**
